version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: kcd-scripts
    versions:
    - 8.0.0
    - 8.0.2
    - 8.1.0
    - 8.1.1
    - 8.2.1
    - 9.0.0
    - 9.1.0
  - dependency-name: dtslint
    versions:
    - 4.0.6
    - 4.0.7
    - 4.0.8
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.2
